### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by stclassy** [stclassy/groceryListBuilder#1]
@pawaitemadisoncollege 
Check point one is ready for review!

Doing the app flow really helped me figure out what was all needed for my project plan. I may have missed a few things there and there but my brain really struggles to plan that far a head and granular like this.

**Comment by pawaitemadisoncollege** [comment]
Hi @stclassy!  This is going to be such a fun and useful project to build!!! 

**Problem statement** Short and to the point! It gets the job done!

**MVP** This seems to be well-scoped and hits the key parts of the project requirements (CRUD). I'm assuming everything is MVP except the admin capability with the question mark. 

- [ ] I saw reference to the recipe scraper in the plan, but didn't see a story for this? 

**Flow** This is great! I think you are right -  it will really help you understand the pieces that need to be built! 

- [ ] I noticed the add Grocery List story has a request going directly to the Dao, without a servlet mentioned. I suspect this is just an oversight as you had servlets well-documented in the other flows. 
- [ ] Some user stories aren't represented in the flow, such as the delete, but maybe this isn't necessary yet?

**Screens** An excellent start! The work you put in here should make building the jsps easier and keep you focused on what's needed.

- [ ] As I mentioned with the flows, some user stories may not be represented in the screens such as the delete.
- [ ] Will the add grocery list screen have fields to enter other than a list name - I didn't see a screen for this so I'm curious about what's involved there?
- [ ] When adding a recipe, will the user be able to add the steps/instructions, or is V1 capturing the ingredients only?

**Project plan** Great details here!  A couple things:

- [ ] In week 7 you will learn how to use AWS cognito for user sign up and log in. It might be worth pushing those user stories back a bit as cognito will take care of some of that work for you. 
- [ ] Consider adding regular deploys to aws.
- [ ] Consider adding the peer reviews and checkpoints, along with implementing feedback that result from those. 

Keep up this great work Sydney!! You've got this!

**Comment by stclassy** [comment]
I am not planning to store recipe instructions at the moment, but am considering fleshing this out into a real app to keep deployed! Everyone I've mentioned my project to have asked if they could use it haha!

**Comment by pawaitemadisoncollege** [comment]
Hi @stclassy - thanks for the clarification - makes good sense for v1!! I can believe everyone wants this! Sign me up too!
